import { type Dimension, type Neighborhood } from './types'

export const neighborhoods: Neighborhood[] = [
  {
    id: 'university-town-center',
    name: 'University Town Center',
    objective: {
      safety: 72,
      transit: 91,
      convenience: 90,
      parking: 54,
      environment: 78,
    },
    perception: {
      safety: 'Generally safe at night near main plazas, occasional bike theft concerns.',
      transit: 'Frequent buses and easy campus access; many users report low car dependence.',
      convenience: 'Very walkable for groceries, food, and study spots.',
      parking: 'Visitor parking can be expensive and difficult during peak hours.',
      environment: 'Active, student-centered area with moderate noise on weekends.',
    },
    redditSampleSize: 86,
    tradeoffNote: 'Excellent transit and convenience, but parking pressure is common.',
  },
  {
    id: 'northwood',
    name: 'Northwood',
    objective: {
      safety: 86,
      transit: 62,
      convenience: 70,
      parking: 84,
      environment: 88,
    },
    perception: {
      safety: 'Residents frequently describe it as quiet and family-friendly.',
      transit: 'Transit is workable but less frequent than central neighborhoods.',
      convenience: 'Good basics nearby, though some errands still require a short drive.',
      parking: 'Street and complex parking are usually easier than denser areas.',
      environment: 'Calm streets, lower noise, and more green space reported.',
    },
    redditSampleSize: 59,
    tradeoffNote: 'Strong safety and environment, weaker transit frequency.',
  },
  {id: 'costa-mesa-border',
    
    name: 'Costa Mesa Border',
    objective: {
      safety: 64,
      transit: 58,
      convenience: 74,
      parking: null,
      environment: 68,
    },
    perception: {
      safety: 'Mixed opinions: some blocks feel safe, others mention late-night caution.',
      transit: 'Most discussions suggest relying on a car for daily routines.',
      convenience: 'Good shopping and food options if driving is available.',
      parking: 'Parking information is inconsistent across postings and complexes.',
      environment: 'More urban feel with variable noise depending on street proximity.',
    },
    redditSampleSize: 37,
    tradeoffNote: 'Decent convenience with higher uncertainty in parking data quality.',
  },
  {
    id: 'irvine-spectrum',
    name: 'Irvine Spectrum',
    objective: {
      safety: 80,
      transit: 85,
      convenience: 95,
      parking: 60,
      environment: 75,
    },
    perception: {
      safety: 'Very safe, well-lit, and patrolled, though busy with visitors.',
      transit: 'Excellent access to train station and freeways.',
      convenience: 'Unbeatable access to shopping, dining, and entertainment.',
      parking: 'Apartment structures have parking, but guest parking is tight.',
      environment: 'Modern and vibrant, but can be noisy due to freeway and crowds.',
    },
    redditSampleSize: 112,
    tradeoffNote: 'Top-tier convenience and modern living at a higher cost and noise level.',
  },
  {
    id: 'woodbridge',
    name: 'Woodbridge',
    objective: {
      safety: 88,
      transit: 65,
      convenience: 78,
      parking: 80,
      environment: 92,
    },
    perception: {
      safety: 'Extremely safe, family-oriented feel with active neighborhood watch.',
      transit: 'Some bus routes, but mostly car-dependent for commuting.',
      convenience: 'Good access to grocery stores and community centers within the loop.',
      parking: 'Generally good street and driveway parking options.',
      environment: 'Beautiful lakes, walking trails, and mature trees define the area.',
    },
    redditSampleSize: 78,
    tradeoffNote: 'Scenic and quiet family atmosphere, but further from major transit hubs.',
  },
  {
    id: 'turtle-rock',
    name: 'Turtle Rock',
    objective: {
      safety: 90,
      transit: 50,
      convenience: 68,
      parking: 85,
      environment: 90,
    },
    perception: {
      safety: 'One of the safest areas in Irvine; very low crime and quiet streets.',
      transit: 'Mostly car-dependent; bus service is limited in this hillside area.',
      convenience: 'Basic necessities accessible by car; UCI campus is nearby.',
      parking: 'Ample residential parking; detached homes with driveways are common.',
      environment: 'Scenic hillside setting with views, trails, and mature landscaping.',
    },
    redditSampleSize: 0,
    tradeoffNote: 'Premium safety and environment in a hillside setting, but requires a car for most errands.',
  },
  {
    id: 'portola-springs',
    name: 'Portola Springs',
    objective: {
      safety: 88,
      transit: 45,
      convenience: 65,
      parking: 88,
      environment: 85,
    },
    perception: {
      safety: 'Very safe, newer master-planned community with controlled access areas.',
      transit: 'Car is essentially required; limited bus routes serve this area.',
      convenience: 'Neighborhood retail nearby, but major shopping requires driving.',
      parking: 'Newer construction with generous garage and driveway parking.',
      environment: 'Modern homes, parks, and open spaces with a suburban feel.',
    },
    redditSampleSize: 0,
    tradeoffNote: 'Safe and modern community with great parking, but very car-dependent.',
  },
  {
    id: 'great-park',
    name: 'Great Park',
    objective: {
      safety: 85,
      transit: 55,
      convenience: 72,
      parking: 82,
      environment: 80,
    },
    perception: {
      safety: 'Newer development with low crime; well-lit streets and active community.',
      transit: 'Some connectivity to the broader Irvine network, but car is preferred.',
      convenience: 'Growing retail and dining options nearby as the area develops.',
      parking: 'Modern construction with structured and surface parking available.',
      environment: 'Adjacent to the Great Park greenspace; open and airy feel.',
    },
    redditSampleSize: 0,
    tradeoffNote: 'Rapidly growing area with good amenities, still maturing transit and retail.',
  },
  {
    id: 'quail-hill',
    name: 'Quail Hill',
    objective: {
      safety: 90,
      transit: 48,
      convenience: 65,
      parking: 86,
      environment: 88,
    },
    perception: {
      safety: 'Gated and semi-gated sections make residents feel very secure.',
      transit: 'Very limited bus service; virtually all trips require a car.',
      convenience: 'Small village shopping center on-site; larger stores a short drive away.',
      parking: 'Mostly attached garages and ample surface lots in the community.',
      environment: 'Hillside open space, hiking trails, and preserved natural areas nearby.',
    },
    redditSampleSize: 0,
    tradeoffNote: 'Upscale, quiet, and scenic — ideal for car owners who value nature access.',
  },
  {
    id: 'oak-creek',
    name: 'Oak Creek',
    objective: {
      safety: 84,
      transit: 60,
      convenience: 75,
      parking: 80,
      environment: 82,
    },
    perception: {
      safety: 'Safe, well-established neighborhood with low incident rates.',
      transit: 'Decent bus connectivity to central Irvine and nearby commercial areas.',
      convenience: 'Well-positioned near major shopping corridors and the 5 freeway.',
      parking: 'Apartment complexes have assigned parking; street parking is manageable.',
      environment: 'Mature trees, manicured common areas, and a golf course nearby.',
    },
    redditSampleSize: 0,
    tradeoffNote: 'Solid all-around neighborhood with better transit access than outer communities.',
  },
  {
    id: 'woodbury',
    name: 'Woodbury',
    objective: {
      safety: 87,
      transit: 50,
      convenience: 70,
      parking: 85,
      environment: 86,
    },
    perception: {
      safety: 'Family-friendly and safe; residents report a strong sense of community.',
      transit: 'Limited transit options; most residents commute by car.',
      convenience: 'Woodbury Town Center provides everyday shopping within walking distance.',
      parking: 'Well-planned community with sufficient parking throughout.',
      environment: 'Abundant parks, paseos, and community pools create a resort-like feel.',
    },
    redditSampleSize: 0,
    tradeoffNote: 'Well-planned suburban community with excellent parks, but car is a must.',
  },
]

export const dimensions: Dimension[] = ['safety', 'transit', 'convenience', 'parking', 'environment']

// Map each dimension to a user-friendly label
export const dimensionLabels: Record<Dimension, string> = {
  safety: 'Safety',
  transit: 'Transit',
  convenience: 'Convenience',
  parking: 'Parking',
  environment: 'Environment',
}
